-- Jalankan seluruh skrip ini pada Supabase SQL Editor.

create table if not exists public.kategori_aset (
  id_kategori bigint generated by default as identity primary key,
  nama_kategori text not null unique
);

create table if not exists public.lokasi (
  id_lokasi bigint generated by default as identity primary key,
  nama_lokasi text not null unique
);

create table if not exists public.kondisi_aset (
  id_kondisi bigint generated by default as identity primary key,
  nama_kondisi text not null unique
);

create table if not exists public.aset (
  id_aset bigint generated by default as identity primary key,
  nama_aset text not null,
  kategori_id bigint not null references public.kategori_aset(id_kategori) on update cascade on delete restrict,
  lokasi_id bigint not null references public.lokasi(id_lokasi) on update cascade on delete restrict,
  kondisi_id bigint not null references public.kondisi_aset(id_kondisi) on update cascade on delete restrict,
  tanggal_pembelian date not null,
  harga_perolehan numeric(15, 2) not null check (harga_perolehan > 0),
  umur_manfaat_tahun integer check (umur_manfaat_tahun is null or umur_manfaat_tahun between 1 and 100),
  nilai_residu numeric(15, 2) not null default 0 check (nilai_residu >= 0 and nilai_residu <= harga_perolehan),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kategori_aset enable row level security;
alter table public.lokasi enable row level security;
alter table public.kondisi_aset enable row level security;
alter table public.aset enable row level security;

-- Tanpa backend dan login: akses CRUD ini terbuka untuk semua pemegang publishable key.
grant usage on schema public to anon;
grant select on public.kategori_aset, public.lokasi, public.kondisi_aset to anon;
grant select, insert, update, delete on public.aset to anon;
grant usage, select on sequence public.aset_id_aset_seq to anon;

drop policy if exists "Public read kategori" on public.kategori_aset;
create policy "Public read kategori" on public.kategori_aset for select to anon using (true);

drop policy if exists "Public read lokasi" on public.lokasi;
create policy "Public read lokasi" on public.lokasi for select to anon using (true);

drop policy if exists "Public read kondisi" on public.kondisi_aset;
create policy "Public read kondisi" on public.kondisi_aset for select to anon using (true);

drop policy if exists "Public read aset" on public.aset;
create policy "Public read aset" on public.aset for select to anon using (true);

drop policy if exists "Public insert aset" on public.aset;
create policy "Public insert aset" on public.aset for insert to anon with check (true);

drop policy if exists "Public update aset" on public.aset;
create policy "Public update aset" on public.aset for update to anon using (true) with check (true);

drop policy if exists "Public delete aset" on public.aset;
create policy "Public delete aset" on public.aset for delete to anon using (true);

create index if not exists aset_kategori_id_idx on public.aset(kategori_id);
create index if not exists aset_lokasi_id_idx on public.aset(lokasi_id);
create index if not exists aset_kondisi_id_idx on public.aset(kondisi_id);

insert into public.kategori_aset (nama_kategori) values
  ('Peralatan Dapur'),
  ('Peralatan Penyajian'),
  ('Kendaraan'),
  ('Peralatan Kantor')
on conflict (nama_kategori) do nothing;

insert into public.lokasi (nama_lokasi) values
  ('Dapur Utama'),
  ('Gudang'),
  ('Kantor'),
  ('Area Pengiriman')
on conflict (nama_lokasi) do nothing;

insert into public.kondisi_aset (nama_kondisi) values
  ('Baik'),
  ('Perlu Perbaikan'),
  ('Rusak')
on conflict (nama_kondisi) do nothing;

insert into public.aset (
  nama_aset, kategori_id, lokasi_id, kondisi_id, tanggal_pembelian, harga_perolehan
)
select
  'Oven konveksi', kategori.id_kategori, lokasi.id_lokasi, kondisi.id_kondisi,
  date '2025-02-12', 12500000
from public.kategori_aset as kategori
cross join public.lokasi as lokasi
cross join public.kondisi_aset as kondisi
where kategori.nama_kategori = 'Peralatan Dapur'
  and lokasi.nama_lokasi = 'Dapur Utama'
  and kondisi.nama_kondisi = 'Baik'
  and not exists (select 1 from public.aset where nama_aset = 'Oven konveksi');

-- Pastikan kolom penyusutan juga ditambahkan pada tabel aset dari instalasi lama.
-- Aset lama tetap memiliki umur_manfaat_tahun NULL sampai diisi lewat form Edit.
alter table public.aset
  add column if not exists umur_manfaat_tahun integer,
  add column if not exists nilai_residu numeric(15, 2) not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'aset_umur_manfaat_tahun_check'
      and conrelid = 'public.aset'::regclass
  ) then
    alter table public.aset
      add constraint aset_umur_manfaat_tahun_check
      check (umur_manfaat_tahun is null or umur_manfaat_tahun between 1 and 100);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'aset_nilai_residu_check'
      and conrelid = 'public.aset'::regclass
  ) then
    alter table public.aset
      add constraint aset_nilai_residu_check
      check (nilai_residu >= 0 and nilai_residu <= harga_perolehan);
  end if;
end
$$;
